### ISSUE TITLE
nginx configuration template still use the hardcoded IP when pull from docker hub

### ISSUE THREAD

**Issue by puffin** [tleyden/sync-gateway-nginx-confd#1]
I saw in your code that you change the configuration template to use the wildcard server_name "_". But when pulled from docker, it still use the hardcoded IP.

ref.: https://github.com/tleyden/sync-gateway-nginx-confd/blob/master/etc/confd/templates/nginx.conf.tmpl#L42

**Comment by tleyden** [comment]
@puffin thanks for the heads up!  I think the problem is that the corresponding [dockerhub repo](https://registry.hub.docker.com/u/tleyden5iwx/sync-gateway-nginx-confd) was not setup for auto-rebuild for changes on this repo.  I fixed that, and kicked off a new build.

Can you retest and reopen this issue if there is still a problem?

**Comment by puffin** [comment]
@tleyden thanks for the quick update! It works now. I'm using your couchbase-cluster-go to setup couchbase on AWS. I'll let you know if I see other issues.

**Comment by puffin** [comment]
@tleyden One more thing. I'm willing to use the new webhooks mechanism introduced in sync_gateway 1.1.0. Is this version the latest official one? On docker the latest tag point to 1.0.4 (https://registry.hub.docker.com/u/couchbase/sync-gateway/tags/manage/). Is is possible to create a new tag to point to https://github.com/couchbase/sync_gateway/releases/tag/1.1.0?

**Comment by tleyden** [comment]
> Is is possible to create a new tag to point to https://github.com/couchbase/sync_gateway/releases/tag/1.1.0?

Yes, will do!  Thanks for the heads up.

Unfortunately, Docker is not yet integrated into our official release process.

**Comment by tleyden** [comment]
@puffin ok I kicked off some new builds on dockerhub, can you check in a bit and let me know if it looks good?

**Comment by tleyden** [comment]
@puffin should be done now.  Please check.

**Comment by puffin** [comment]
@tleyden Thanks! It pulls correctly the latest version now. I still struggle to use the webhook event_handlers as nothing is sent to the endpoint url on document change. I followed this post http://blog.couchbase.com/sync-gateway-webhooks

**Comment by tleyden** [comment]
Can you file a separate ticket in https://github.com/couchbase/sync_gateway for that?

**Comment by puffin** [comment]
@tleyden yep sure

**Comment by puffin** [comment]
Sorry to come again in this thread but I suspect the docker build `latest` for sync_gateway (https://registry.hub.docker.com/u/couchbase/sync-gateway/builds_history/188654/) still points to 1.0.4 instead of 1.1.0. After pulling the image and building my docker container, the sync_gateway returns me this version: `"Couchbase Sync Gateway/HEAD(nobranch)(04138fd)"`which correspond to the tag 1.0.4 on github (https://github.com/couchbase/sync_gateway/releases/tag/1.0.4).

**Comment by tleyden** [comment]
@puffin you're right -- I'm seeing the same thing:

```
$ docker pull couchbase/sync-gateway
$ docker run couchbase/sync-gateway
15:36:25.474100 ==== Couchbase Sync Gateway/HEAD(nobranch)(04138fd) ====
```

Looking into it

**Comment by tleyden** [comment]
This does the right thing:

```
docker run couchbase/sync-gateway:1.1.0
```

Everything looks right on dockerhub.  I kicked off another build, if that doesn't work, I'll email support.

**Comment by tleyden** [comment]
OK it looks to be fixed.  @puffin can you confirm?

**Comment by puffin** [comment]
I confirmed it's fixed. Thanks for the awesome support!
